name: Deploy ru.svelte.dev

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/workflows/deploy-kit.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Installing deps
        run: npm install

      - name: Build translated site
        run: npm run build:svelte

      - name: Copy Dockerfile to build dir
        run: cp docker/Dockerfile __BUILD/sites/svelte.dev/build/

      - name: Packing to archive
        run: cd __BUILD/sites/svelte.dev/build && tar -czvf files.tar.gz ./*

      - name: Copy build dir to the server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: __BUILD/sites/svelte.dev/build/files.tar.gz
          remote: /tmp/svelte.dev/files.tar.gz
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}

      - name: Build and start Docker container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /tmp/svelte.dev
            tar -xvf files.tar.gz && rm files.tar.gz
            docker build -t svelte-site .
            docker stop Svelte-Site
            docker rm Svelte-Site
            docker run -d \
                -p 3003:3000 \
                --name Svelte-Site \
                --restart=unless-stopped \
                --env GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} \
                --env GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} \
                --env VITE_MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }} \
                --env SUPABASE_URL=123 \
                --env SUPABASE_KEY=123 \
            svelte-site
            rm -rf /tmp/svelte.dev
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}